SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

LARGE_ASTEROID_MIN_RADIUS = 50
MEDIUM_ASTEROID_MIN_RADIUS = 20

LARGE_RADIUS = 60
LARGE_VELOCITY = 5

MEDIUM_RADIUS = 30
MEDIUM_VELOCITY = 7

SMALL_RADIUS = 10
SMALL_VELOCITY = 9

PLAYER_RADIUS  = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5


